draw_set_font(f_big)
draw_set_halign(fa_center)
draw_set_alpha(.85)
draw_set_font(f_main)
draw_text(room_width/2,100,gameOverText)
draw_set_font(f_big)
draw_set_valign(fa_center)
draw_text(room_width/2,room_height/2,"Score: " + string(score))
draw_set_font(f_main)
draw_set_alpha(.5)
draw_set_font(f_small)
draw_text(room_width/2 - 20,room_height/2 + 340,"Press 'R' to Try Again")
draw_text(room_width/2 - 20,room_height/2 + 420,"Press 'M' to Go to the Main Menu")
draw_set_alpha(1)